---
appveyor.yml:
  delete: true

CONTRIBUTING.md:
  unmanaged: true

.gitignore:
  paths:
    - 'examples/client_ffdc/'
    - 'client_ffdc'

Gemfile:
  optional:
    ':development':
      - gem: 'rototiller'
        version: '0.1.0'
    ':system_tests':
      - gem: 'beaker-testmode_switcher'

LICENSE:
  license_type: 'puppetpe'

Rakefile:
  unmanaged: true

spec/acceptance/nodesets/default.yml:
  unmanaged: true

spec/acceptance/nodesets/centos-7-x64.yml:
  unmanaged: true

spec/acceptance/nodesets/debian-8-x64.yml:
  unmanaged: true

spec/acceptance/nodesets/docker/centos-7.yml:
  unmanaged: true

spec/acceptance/nodesets/docker/ubuntu-14.04.yml:
  unmanaged: true

spec/acceptance/nodesets/docker/debian-8.yml:
  unmanaged: true

spec/spec_helper.rb:
  allow_deprecations: true

.travis.yml:
  docker_sets: []
